environment: production
chdir: /home/acoplet/www/acoplet/current/
address: 127.0.0.1
user: acoplet
group: acoplet
port: 4567
pid: /home/acoplet/www/acoplet/current/tmp/thin.pid
rackup: /home/acoplet/www/acoplet/current/config.ru
log: /home/acoplet/www/acoplet/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true