environment: production
chdir: /home/acoplet/wwwls/mert/current/
address: 127.0.0.1
user: root
group: root
port: 4567
pid: /home/acoplet/wwwls/mert/current/tmp/thin.pid
rackup: /home/acoplet/wwwls/mert/current/config.ru
log: /home/acoplet/wwwls/mert/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true